repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run Tests
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false

      - id: remove-traces
        name: Remove pdb/ipdb trace statements and run Black
        entry: python remove_traces.py
        language: python
        files: \.py$

      - id: check-for-debugger
        name: Check for pdb.set_trace and ipdb.set_trace
        entry: bash -c 'FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E ".py$"); if [ -n "$FILES" ]; then grep -Hn "pdb.set_trace\|ipdb.set_trace" $FILES && echo "Debugger statement found!" && exit 1; fi; exit 0'
        language: system
        types: [python]
        files: \.py$ 

  - repo: https://github.com/psf/black
    rev: 24.4.2 
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
        args: ["--check"]
        additional_dependencies: ["black"]

