repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2 
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
        args: ["--check"]
        additional_dependencies: ["black"]

  - repo: local
    hooks:
      - id: run-tests
        name: Run Tests
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false

      - id: check-for-debugger
        name: Check for pdb.set_trace and ipdb.set_trace
        entry: bash -c 'for file in "$@"; do if grep -qE "pdb.set_trace\(\)|ipdb.set_trace\(\)" "$file"; then echo "Debugger statement found in $file!"; exit 1; fi; done;'
        language: system
        types: [python]
        files: \.py$

