repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
        args: ["--check"]

  - repo: local
    hooks:
      - id: run-tests
        name: Run Tests
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
