defaults:
- _self_
llm:
  _target_: langchain_anthropic.ChatAnthropic
  model: claude-3-5-sonnet-20240620 
  temperature: 1
prompt_loader:
  _target_: src.prompts.yaml_prompt_loader.YamlPromptLoader
  yaml_path: ${prompts.path}
prompts:
  path: src/prompts/prompts.yaml
user:
  thread_id: ${user.user_id}
  user_id: 2670468f-e089-4986-87f9-e02af6a9dc13 
