defaults:
- _self_
llm:
  _target_: langchain_anthropic.ChatAnthropic
  model: claude-3-sonnet-20240229
  temperature: 1
prompt_loader:
  _target_: src.prompts.yaml_prompt_loader.YamlPromptLoader
  yaml_path: ${prompts.path}
prompts:
  path: src/prompts/prompts.yaml
user:
  thread_id: ${user.user_id}
  user_id: 5c37d5ca-b80c-407a-8310-982ca5c06c8f
